# version 2020.8.23
# version 2020.9.21, add classification information
# version 2021.1.7, add (step 15) icamp.cate to summarize for different categories of taxa, e.g. core versus rare taxa.
# version 2021.4.17, add step 9.5 and 9.6.
# version 2023.7.4, add step 9.3.2

rm(list=ls())
t0=Sys.time() # to calculate time cost

# 1 # set folder paths and file names, please change according to the folder paths and file names in your computer.
# the folder saving the input files
wd="F:/iCAMP_NPSS+PSS/Archaea"

# the OTU table file (Tab delimited txt file)
com.file<- read.csv("F:/iCAMP_NPSS+PSS/Archaea/Archaea.csv", header = TRUE, row.names = 1, 
                    check.names = FALSE, stringsAsFactors = FALSE)
com.file<- t(com.file)
com.file<- com.file[com.file[, 1] != "", ]
cat("清洗后维度:", dim(com.file), "\n")

# the phylogenetic tree file
tree.file="Archaea_tree.nwk"

# the classification (taxonomy) information
clas.file="Archaea_classification.csv"

# the treatment informaiton table
treat.file="sample_groups.csv"

# the environmental varialbes
env.file="soil_properties.csv"
# if you do not have env file or the env may not represent niche, skip step 7 and 8, but check the alternative way to determine binning setting, e.g. bin.size.limit.

# the folder to save the output. please change to a new folder even if you are just testing the example data.
save.wd="F:/iCAMP_NPSS+PSS/Archaea/Archaea_iCAMP_ analysis"
if(!dir.exists(save.wd)){dir.create(save.wd)}

# 2 # key parameter setting
prefix="Test"  # prefix of the output file names. usually use a project ID.
rand.time=100  # randomization time, 1000 is usually enough. For example test, you may set as 100 or less to save time.
nworker=4 # nworker is thread number for parallel computing, which depends on the CPU core number of your computer.
memory.G=50 # to set the memory size as you need (but should be less than the available space in your hard disk), so that calculation of large tree will not be limited by physical memory. unit is Gb.

# 3 # load R packages and data
install.packages("iCAMP")
library(iCAMP)
library(ape)
setwd(wd)
comm <- com.file
tree=read.tree(file = tree.file)
clas=read.csv(clas.file, header = TRUE, row.names = 1,
              as.is = TRUE, stringsAsFactors = FALSE, comment.char = "",
              check.names = FALSE)
treat=read.csv(treat.file, header = TRUE, row.names = 1,
               as.is = TRUE, stringsAsFactors = FALSE, comment.char = "",
               check.names = FALSE)

env=read.csv(env.file, header = TRUE, row.names = 1,
             as.is = TRUE, stringsAsFactors = FALSE, comment.char = "",
             check.names = FALSE) # skip this if you do not have env.file

# 4 # match sample IDs in OTU table and treatment information table
sampid.check=match.name(rn.list=list(comm=comm,treat=treat,env=env))
# sampid.check=match.name(rn.list=list(comm=comm,treat=treat)) # if you do not have env.file
# for the example data, the output should be "All match very well".
# for your data files, if you have not matched their IDs, the unmatched samples will be removed.
treat=sampid.check$treat
comm=sampid.check$comm
comm=comm[,colSums(comm)>0,drop=FALSE] # if some unmatched samples were removed, some OTUs may become ghosts, then you may use this line to remove them if necessary.
env=sampid.check$env # skip this if you do not have env.file

# 5 # match OTU IDs in OTU table and tree file
spid.check=match.name(cn.list=list(comm=comm),rn.list=list(clas=clas),tree.list=list(tree=tree))
# for the example data, the output should be "All match very well".
# for your data files, if you have not matched the IDs before, the unmatched OTUs will be removed.
comm=spid.check$comm
clas=spid.check$clas
tree=spid.check$tree

# 6 # calculate pairwise phylogenetic distance matrix.
# since microbial community data usually has a large number of species (OTUs or ASVs), we use "big.matrix" in R package "bigmemory" to handle the large phylogenetic distance matrix. 
setwd(save.wd)
if(!file.exists("pd.desc")) 
{
  pd.big=iCAMP::pdist.big(tree = tree, wd=save.wd, nworker = nworker, memory.G = memory.G)
  # output files:
  # path.rda: a R object to list all the nodes and  edge lengthes from root to every tip. saved in R data format. an intermediate output when claculating phylogenetic distance matrix.
  # pd.bin: BIN file (backingfile) generated by function big.matrix in R package bigmemory. This is the big matrix storing pairwise phylogenetic distance values. By using this bigmemory format file, we will not need memory but hard disk when calling big matrix for calculation.
  # pd.desc: the DESC file (descriptorfile) to hold the backingfile (pd.bin) description.
  # pd.taxon.name.csv: comma delimited csv file storing the IDs of tree tips (OTUs), serving as the row/column names of the big phylogenetic distance matrix.
}else{
  # if you already calculated the phylogenetic distance matrix in a previous run
  pd.big=list()
  pd.big$tip.label=read.csv(paste0(save.wd,"/pd.taxon.name.csv"),row.names = 1,stringsAsFactors = FALSE)[,1]
  pd.big$pd.wd=save.wd
  pd.big$pd.file="pd.desc"
  pd.big$pd.name.file="pd.taxon.name.csv"
}

####################
# you may skip step 7-8, if the "alternative way" based on stochasticity is applicable, as mentioned in the method part of iCAMP paper (Ning et al 2020 Nature Communications).
# 7 # assess niche preference difference between species
# env is required for this step.
# since microbial community data usually has a large number of species (OTUs or ASVs), we use "big.matrix" in R package "bigmemory" to handle the large niche difference matrix. 
setwd(save.wd)
niche.dif=iCAMP::dniche(env = env,comm = comm,method = "niche.value",
                        nworker = nworker,out.dist=FALSE,bigmemo=TRUE,
                        nd.wd=save.wd)

# 8 # within-bin phylogenetic signal assessment.
# For real data, you may try several different settings of binning, and choose the one leading to the best within-bin phylogenetic signal.
# env is required for this step.
# 8.1 # try phylogenetic binning using current setttings.
ds = 0.2 # setting can be changed to explore the best choice
bin.size.limit = 5 # setting can be changed to explore the best choice. # here set as 5 just for the small example dataset. For real data, usually try 12 to 48.

# The tree for taxa.binphy.big must be a rooted tree.
if(!ape::is.rooted(tree))
{
  tree.rt=iCAMP::midpoint.root.big(tree = tree, pd.desc = pd.big$pd.file,
                                   pd.spname = pd.big$tip.label,pd.wd = pd.big$pd.wd,
                                   nworker = nworker)
  tree=tree.rt$tree
}
phylobin=taxa.binphy.big(tree = tree, pd.desc = pd.big$pd.file,pd.spname = pd.big$tip.label,
                         pd.wd = pd.big$pd.wd, ds = ds, bin.size.limit = bin.size.limit,
                         nworker = nworker)
# 8.2 # test within-bin phylogenetic signal.
sp.bin=phylobin$sp.bin[,3,drop=FALSE]
sp.ra=colMeans(comm/rowSums(comm))
abcut=3 # you may remove some species, if they are too rare to perform reliable correlation test.
commc=comm[,colSums(comm)>=abcut,drop=FALSE]
dim(commc)
spname.use=colnames(commc)
binps=iCAMP::ps.bin(sp.bin = sp.bin,sp.ra = sp.ra,spname.use = spname.use,
                    pd.desc = pd.big$pd.file, pd.spname = pd.big$tip.label, pd.wd = pd.big$pd.wd,
                    nd.list = niche.dif$nd,nd.spname = niche.dif$names,ndbig.wd = niche.dif$nd.wd,
                    cor.method = "pearson",r.cut = 0.1, p.cut = 0.05, min.spn = 5)
if(file.exists(paste0(prefix,".PhyloSignalSummary.csv"))){appendy=TRUE;col.namesy=FALSE}else{appendy=FALSE;col.namesy=TRUE}
write.table(data.frame(ds=ds,n.min=bin.size.limit,binps$Index),file = paste0(prefix,".PhyloSignalSummary.csv"),
            append = appendy, quote=FALSE, sep=",", row.names = FALSE,col.names = col.namesy)
if(file.exists(paste0(prefix,".PhyloSignalDetail.csv"))){appendy2=TRUE;col.namesy2=FALSE}else{appendy2=FALSE;col.namesy2=TRUE}
write.table(data.frame(ds=ds,n.min=bin.size.limit,binID=rownames(binps$detail),binps$detail),file = paste0(prefix,".PhyloSignalDetail.csv"),
            append = appendy2, quote = FALSE, sep = ",", row.names = FALSE, col.names = col.namesy2)
# since this example small data is randomly generated, the correlation should be very weak.
# usually, you are looking for a binning setting lead to higher RAsig.abj (relative abundance of bins with significant phylogenetic signal) and relative high meanR (mean correlation coefficient across bins).
rbind(
  binps$Index[binps$Index$index == "RAsig.adj", ],
  binps$Index[binps$Index$index == "MeanR.sig", ]
)
# see help document of the function "ps.bin" for the meaning of output.


####################
# 9 # iCAMP analysis
# 9.1 # without omitting small bins.
# commonly use # set sig.index as Confidence instead of SES.RC (betaNRI/NTI + RCbray)
bin.size.limit = 5 # For real data, usually use a proper number according to phylogenetic signal test or try some settings then choose the reasonable stochasticity level. our experience is 12, or 24, or 48. but for this example dataset which is too small, have to use 5.
sig.index="Confidence" # see other options in help document of icamp.big.
icres=iCAMP::icamp.big(comm=comm, pd.desc = pd.big$pd.file, pd.spname=pd.big$tip.label,
                       pd.wd = pd.big$pd.wd, rand = rand.time, tree=tree,
                       prefix = prefix, ds = 0.2, pd.cut = NA, sp.check = TRUE,
                       phylo.rand.scale = "within.bin", taxa.rand.scale = "across.all",
                       phylo.metric = "bMPD", sig.index=sig.index, bin.size.limit = bin.size.limit, 
                       nworker = nworker, memory.G = memory.G, rtree.save = FALSE, detail.save = TRUE, 
                       qp.save = FALSE, detail.null = FALSE, ignore.zero = TRUE, output.wd = save.wd, 
                       correct.special = TRUE, unit.sum = rowSums(comm), special.method = "depend",
                       ses.cut = 1.96, rc.cut = 0.95, conf.cut=0.975, omit.option = "no",meta.ab = NULL)
# there are quite a few parameters in this function, please check the help document of "icamp.big".
# output files:
# Test.iCAMP.detail.rda: the object "icres" saved in R data format. it is a list object. The first element bNRIiRCa is the result of relative importance of each assembly process in each pairwise comparison (each turnover). The second element "detail" including binning information (named taxabin), phylogenetic and taxonomic metrics results in each bin (named like bNRIi, RCa, etc.), relative abundance of each bin (bin.weight), relative importance of each process in each turnover between communities (processes), input settings (setting), and input community data matrix (comm). See help document of the function icamp.big for more details.

###############################
# 10 # iCAMP bin level statistics
icbin=iCAMP::icamp.bins(icamp.detail = icres$detail,treat = treat,
                        clas=clas,silent=FALSE, boot = TRUE,
                        rand.time = rand.time,between.group = TRUE)
save(icbin,file = paste0(prefix,".iCAMP.Summary.rda")) # just to archive the result. rda file is automatically compressed, and easy to load into R.
write.csv(icbin$Pt,file = paste0(prefix,".ProcessImportance_EachGroup.csv"),row.names = FALSE)
write.csv(icbin$Ptk,file = paste0(prefix,".ProcessImportance_EachBin_EachGroup.csv"),row.names = FALSE)
write.csv(icbin$Ptuv,file = paste0(prefix,".ProcessImportance_EachTurnover.csv"),row.names = FALSE)
write.csv(icbin$BPtk,file = paste0(prefix,".BinContributeToProcess_EachGroup.csv"),row.names = FALSE)
write.csv(data.frame(ID=rownames(icbin$Class.Bin),icbin$Class.Bin,stringsAsFactors = FALSE),
          file = paste0(prefix,".Taxon_Bin.csv"),row.names = FALSE)
write.csv(icbin$Bin.TopClass,file = paste0(prefix,".Bin_TopTaxon.csv"),row.names = FALSE)

# output files:
# Test.iCAMP.Summary.rda: the object "icbin" saved in R data format. see help document of the function icamp.bins for description of each element in the object.
# Test.ProcessImportance_EachGroup.csv: Relative importance of each process in governing the turnovers in a group of samples.
# Test.ProcessImportance_EachBin_EachGroup.csv: Relative importance of each process in governing the turnovers of each bin among a group of samples.
# Test.ProcessImportance_EachTurnover.csv: Relative importance of each process in governing the turnovers between each pair of communities (samples).
# Test.BinContributeToProcess_EachGroup.csv: Bin contribution to each process, measuring the contribution of each bin to the relative importance of each process in the assembly of a group of communities.
# Test.Taxon_Bin.csv: a matrix showing the bin ID and classification information for each taxon.
# Test.Bin_TopTaxon.csv: a matrix showing the bin relative abundance; the top taxon ID, percentage in bin, and classification; the most abundant name at each phylogeny level in the bin.

# 11 # Bootstrapping test
# please specify which column in the treatment information table.
i=1
treat.use=treat[,i,drop=FALSE]
icamp.result=icres$CbMPDiCBraya
icboot=iCAMP::icamp.boot(icamp.result = icamp.result,treat = treat.use,rand.time = rand.time,
                         compare = TRUE,silent = FALSE,between.group = TRUE,ST.estimation = TRUE)
save(icboot,file=paste0(prefix,".iCAMP.Boot.",colnames(treat)[i],".rda"))
write.csv(icboot$summary,file = paste0(prefix,".iCAMP.BootSummary.",colnames(treat)[i],".csv"),row.names = FALSE)
write.csv(icboot$compare,file = paste0(prefix,".iCAMP.Compare.",colnames(treat)[i],".csv"),row.names = FALSE)

# output files:
# Test.iCAMP.Boot.Management.rda: the object "icboot" saved in R data format. see help document of the function icamp.boot for description of each element in the object.
# Test.BootSummary.Management.csv: a table to summarize bootstrapping results. see help document of the function icamp.boot for description of the output element "summary".
# Test.Compare.Management.csv: a table to summarize comparison index, effect size, and significance between each two groups. see help document of the function icamp.boot for description of the output element "compare".

# End #

# ========================
# 0. 加载所需包
# ========================
library(ggplot2)
library(ggtree)
library(ggtreeExtra)
library(phyloseq)
library(dplyr)
library(tidyr)
library(picante)
library(ggnewscale)   # 用于分离图例

#if (!requireNamespace("BiocManager", quietly = TRUE))
#install.packages("BiocManager")
#BiocManager::install("ggtree")
#BiocManager::install("phyloseq")
#if (!requireNamespace("remotes", quietly = TRUE))
#install.packages("remotes")
#remotes::install_github("YuLab-SMU/ggtreeExtra")

# ========================
# 1. 数据准备与 phyloseq 对象构建（保持不变）
# ========================
# 读取 OTU 表、分类表、元数据和进化树
otu <- read.csv("F:/iCAMP_NPSS+PSS/Archaea/Archaea.csv", header = TRUE, row.names = 1,  stringsAsFactors = FALSE)
taxa <- read.csv("F:/iCAMP_NPSS+PSS/Archaea/Archaea_classification.csv", header = TRUE, row.names = 1,  stringsAsFactors = FALSE)
metadata <- read.csv("F:/iCAMP_NPSS+PSS/Archaea/sample_groups.csv", header = TRUE, row.names = 1, stringsAsFactors = FALSE)
tree <- read.tree("F:/iCAMP_NPSS+PSS/Archaea/Archaea_tree.nwk")


# 转换为矩阵
otu <- as.matrix(otu)
taxa <- as.matrix(taxa)

# 确保样本名一致（顺序可以不同，但集合必须相同）
common_samples <- intersect(colnames(otu), rownames(metadata))
if(length(common_samples) != ncol(otu) || length(common_samples) != nrow(metadata)){
  warning("样本名不完全匹配，将取交集")
  otu <- otu[, common_samples, drop = FALSE]
  metadata <- metadata[common_samples, , drop = FALSE]
}

# 确保OTU/ASV名一致
common_otus <- intersect(rownames(otu), rownames(taxa))
if(length(common_otus) != nrow(otu) || length(common_otus) != nrow(taxa)){
  warning("OTU名不完全匹配，将取交集")
  otu <- otu[common_otus, , drop = FALSE]
  taxa <- taxa[common_otus, , drop = FALSE]
  # 树也需要同步修剪
  tree <- keep.tip(tree, common_otus)
}

# 构建 phyloseq 对象
otu_table_obj <- otu_table(otu, taxa_are_rows = TRUE)
tax_table_obj <- tax_table(taxa)
sample_data_obj <- sample_data(metadata)
physeq <- phyloseq(otu_table_obj, tax_table_obj, sample_data_obj, tree)

# 检查一下文件对不对
summary(physeq)
nsamples(physeq)
ntaxa(physeq)

# 读取bins信息
bins <- read.csv("F:/iCAMP_NPSS+PSS/Archaea/Archaea_iCAMP_ analysis/Test.Bin_TopTaxon.csv", row.names = 1, header = TRUE)
bins_assembly <- read.csv("F:/iCAMP_NPSS+PSS/Archaea/Archaea_iCAMP_ analysis/Test.ProcessImportance_EachBin_EachGroup.csv", header = TRUE)
bins_assembly <- bins_assembly[1:5, 4:ncol(bins_assembly)]

# 提取bin的“主干”
bin_otu_ids <- bins[, "TopTaxonID"]
physeq <- prune_taxa(bin_otu_ids, physeq)

bins_map <- bins[, "TopTaxonID", drop = FALSE]
bins_map <- bins_map[match(taxa_names(physeq), bins_map$TopTaxonID), , drop = FALSE]
identical(bins_map$TopTaxonID, taxa_names(physeq))
taxa_names(physeq) <- rownames(bins_map)

# 准备组装数据
bins_assembly <- as.data.frame(t(bins_assembly))
colnames(bins_assembly) <- as.character(unlist(bins_assembly[1, ]))
rownames(bins_map) <- tolower(rownames(bins_map))
bins_assembly <- bins_assembly[match(rownames(bins_map), rownames(bins_assembly)), , drop = FALSE]

bins_assembly_new <- bins_assembly %>% 
  tibble::rownames_to_column(var = "bin")
bins_assembly_new$bin <- sub("^b", "B", bins_assembly_new$bin)
bins_assembly_new$HeS <- as.numeric(bins_assembly_new$HeS)
bins_assembly_new$HoS <- as.numeric(bins_assembly_new$HoS)
bins_assembly_new$DL <- as.numeric(bins_assembly_new$DL)
bins_assembly_new$HD <- as.numeric(bins_assembly_new$HD)
bins_assembly_new$DR <- as.numeric(bins_assembly_new$DR)

# 导入bins的相对丰度
bins_RA <- read.csv("F:/iCAMP_NPSS+PSS/Archaea/Archaea_iCAMP_ analysis/Test.Bin_TopTaxon.csv", row.names = 1, header = TRUE)
rownames(bins_RA) <- tolower(rownames(bins_RA))
bins_RA <- bins_RA[rownames(bins_map), , drop = FALSE]
rownames(bins_RA) <- sub("^b", "B", rownames(bins_RA))

bins_RA_new <- bins_RA %>% 
  tibble::rownames_to_column(var = "bin")

# 筛选top10的phylum
summarized_data <- bins_RA_new %>% 
  group_by(TopTaxon.Phylum) %>% 
  summarise(total_RA = sum(BinRA)) %>% 
  ungroup() %>% 
  arrange(desc(total_RA))
top_phyla <- summarized_data$TopTaxon.Phylum[1:10]

bins_RA_new <- bins_RA_new %>% 
  mutate(Phylum = ifelse(TopTaxon.Phylum %in% top_phyla, TopTaxon.Phylum, "others"))

# 更新 tax_table
tax_table_df <- as.data.frame(physeq@tax_table)
original_rownames <- rownames(tax_table_df)
original_colnames <- colnames(tax_table_df)
tax_table_df$Phylum <- ifelse(tax_table_df$Phylum %in% top_phyla, tax_table_df$Phylum, "others")
new_physeq <- physeq
new_physeq@tax_table <- tax_table(tax_table_df)
rownames(new_physeq@tax_table) <- original_rownames
colnames(new_physeq@tax_table) <- original_colnames

# 整理bin的metadata
bins_info <- cbind(bins_assembly, bins_RA_new$BinRA)
bins_info <- cbind(bins_info, bins_RA_new$Phylum)
rownames(bins_info) <- bins_assembly_new$bin
colnames(bins_info) <- c("HeS", "HoS", "DL", "HD", "DR", "binsRA", "Phylum")

# 提取树并匹配数据
new_tree <- phy_tree(physeq)
metaplot <- match.phylo.data(new_tree, bins_info$Phylum)
treeWithInfo <- metaplot$phy 

# 设置门水平颜色（包含 "others"）
colors <- c("#F57F20", "#1DBB95", "#51B1DF", "#C77DFF", "#9D0208", "#F08080", "#007F5F", "#80B918",  "#90E0EF","#E66F73","#F57F20","#1DBB95","#9CB79F","#F0B8D2","#A0485E","#A0688E","#C7E1DF","#51B1DF","#6D97D7","#5D6193","#CEC3E0")
phylum_colors <- setNames(colors[1:length(top_phyla)], top_phyla)
if(!"others" %in% names(phylum_colors)) {
  phylum_colors <- c(phylum_colors, "others" = "gray80")
}

# 构建 group 映射（按门）
groupInfo1 <- split(treeWithInfo$tip.label, as.vector(bins_info$Phylum))
treeWithInfo <- groupOTU(treeWithInfo, groupInfo1)

# 转换为长格式（用于堆叠柱状图）
bins_assembly_long <- bins_assembly_new %>% 
  pivot_longer(cols = c(HeS, HoS, DL, HD, DR),
               names_to = "Category",
               values_to = "Percentage")

# 定义组装过程颜色集
category_colors <- c(
  "HeS" = "#F7B774",
  "HoS" = "#E55C3C",
  "DL"  = "#74A9CB",
  "HD"  = "#C7E6EF",
  "DR"  = "#3B54A4"
)

# ========================
# ========================
# 3. 辐射树 + 堆叠柱状图
# ========================

# 快速查看生态过程数据的分布
#hist(bins_assembly_long$Percentage, 
     #main = "Distribution of ecological processes", 
     #xlab = "Percentage")

# 查看相对丰度的分布
#hist(bins_RA_new$BinRA, 
     #main = "Distribution of relative abundance", 
     #xlab = "Relative abundance")
# ========================

p21 <- ggtree(treeWithInfo,
              aes(color = group),
              layout = "radial",
              branch.length = 'none',
              open.angle = 10,
              lwd = 1) +
  geom_tiplab(aes(color = group), offset = 12, size = 3, show.legend = FALSE) +
  scale_color_manual(values = phylum_colors, guide = "none")
p21 <- rotate_tree(p21, -90)
p21
# 动态计算合适的 step
p22 <- p21 + 
  geom_fruit(data = bins_assembly_long,
             geom = geom_col,
             mapping = aes(y = bin, x = Percentage, fill = Category),
             pwidth = 0.7,
             width = 0.5,
             offset = 0,
             # 添加比例尺（坐标轴）
             axis.params = list(
               axis = "x",  # 显示x轴
               title = "Proportion",  # 轴标题
               title.size = 2,  # 标题字体大小
               text.size = 2,  # 刻度标签字体大小
               vjust = 0.5,  # 垂直位置
               step = 0.2,  # 刻度步长（根据实际数据范围调整，如0,20,40,60,80,100）
               orient = "bottom"
             )) +
  scale_fill_manual(name = "Ecological processes", values = category_colors)
p22
p23 <- p22 + 
  new_scale_fill() +
  geom_fruit(data = bins_RA_new,
             geom = geom_col,
             mapping = aes(y = bin, x = BinRA, fill = Phylum),
             pwidth = 1.2,
             width = 0.5,
             offset = 0.23,
             # 添加比例尺（坐标轴）
             axis.params = list(
               axis = "x",  # 显示x轴
               title = "Relative abundance",  # 轴标题
               title.size = 2,  # 标题字体大小
               text.size = 2,  # 刻度标签字体大小
               vjust = 0.5,  # 垂直位置
               step = 0.2,  # 刻度步长（根据实际数据范围调整）
               orient = "bottom"
             )) +
  scale_fill_manual(name = "Phylum", values = phylum_colors) +
  theme(legend.position = "right")
p23
ggsave("F:/iCAMP_NPSS+PSS/Archaea/Archaea_icamp_radial_tree.pdf", plot = p23, dpi = 1200, width = 8, height = 8)

# 完成
# ========================
